version: "3.0"

language: br

# See https://rasa.com/docs/rasa/tuning-your-model for more information.
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 80
  model_confidence: softmax
  constrain_similarities: true
  tensorboard_log_directory: ".tensorboard_diet"
  tensorboard_log_level: "epoch"
- name: EntitySynonymMapper
- name: ResponseSelector
  model_confidence: softmax
  epochs: 100
  constrain_similarities: true
- name: FallbackClassifier
  threshold: 0.7
  ambiguity_threshold: 0.2

# https://rasa.com/docs/rasa/core/policies/
policies:
- name: RulePolicy
  core_fallback_threshold: 0.1
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: false
- name: MemoizationPolicy
  max_history: 5
- name: TEDPolicy
  max_history: 5
  epochs: 100
  priority: 2
assistant_id: 20250222-004123-serious-bulb
