version: '3.8'

services:

  bot:
    depends_on:
      - postgres
      - action_server
    build:
      context: .
      dockerfile: ./docker/Dockerfile    
    volumes:
      - .:/app
    entrypoint: '/app/docker/entrypoint.sh'
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: banco
      POSTGRES_HOST: postgres
      RASA_CACHE: disabled
     
    ports:
      - '5005:5005'

  action_server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile    
    volumes:
      - .:/app
    command:
      - 'run'
      - 'actions'
      - '--debug'
    ports: 
      - '5055:5055'
    user: root
  
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: banco
      POSTGRES_INITDB_ARGS: "--locale-provider=libc"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
