version: '3.8'

services:

  bot:
    depends_on:
      - postgres
      - action_server
    build:
      context: .
      dockerfile: ./docker/Dockerfile    
    volumes:
      - .:/app
    entrypoint: '/app/docker/entrypoint.sh'
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: banco
      POSTGRES_HOST: postgres
      RASA_CACHE: disabled
      WORDPRESS_URL: wordpress
    networks:
      - interna
 
    ports:
      - '5005:5005'

  action_server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile    
    environment:
      WORDPRESS_URL: http://wordpress
    volumes:
      - .:/app
    command:
      - 'run'
      - 'actions'
      - '--debug'
    ports: 
      - '5055:5055'
    user: root
    networks:
      - wordpress-bot
      - interna


  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: banco
      POSTGRES_INITDB_ARGS: "--locale-provider=libc"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - interna

networks:
  interna:
    driver: bridge
  wordpress-bot:
    external: true
